# Generated by Django 2.1.3 on 2018-12-03 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0002_atm_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='atm',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='atm',
            name='refillDate',
            field=models.DateField(default=datetime.datetime(2018, 12, 2, 20, 59, 37, 83550)),
        ),
        migrations.AlterField(
            model_name='atm',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
