# Generated by Django 2.1.3 on 2018-12-04 01:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0004_auto_20181203_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATMCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateofissue', models.DateField()),
                ('expiration', models.DateField()),
                ('num', models.IntegerField()),
                ('pin', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')])),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ATM.User'),
        ),
        migrations.AlterField(
            model_name='atm',
            name='Lrefill',
            field=models.DateField(default=datetime.datetime(2018, 12, 3, 20, 24, 14, 615364)),
        ),
        migrations.AlterField(
            model_name='atm',
            name='NrefillDate',
            field=models.DateField(default=datetime.datetime(2018, 12, 3, 20, 24, 14, 616364)),
        ),
        migrations.AddField(
            model_name='atmcard',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATM.Account'),
        ),
    ]
